/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
static yyconst short int yy_accept[316] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       34,   34,   32,   32,   38,   33,   33,   36,   31,   30,
       33,   33,   33,   33,    7,    8,   35,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,    9,   33,   33,
       31,   30,   32,   32,   31,   30,    0,   31,    0,    0,
        2,    0,    0,    1,    7,    8,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    9,   34,   34,
       31,   32,   32,   31,    0,    2,    0,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   25,
        0,    0,    0,    0,    0,   10,    0,    0,    0,    0,
        0,    0,   17,    0,    0,    0,    0,    0,    0,    0,
        0,   25,    0,    0,    0,    0,   26,    0,    0,   10,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   17,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   26,    0,    0,    0,    0,    0,    0,

        0,    0,   12,    0,    0,    0,   11,    0,    0,    0,
        0,   15,    0,    0,    0,    0,    0,    0,    0,   21,
        0,    0,    0,    0,    0,    5,    0,    0,    0,    0,
        0,   26,    0,   27,    0,    0,   13,   12,    0,   11,
        0,    0,   15,    0,    0,    0,   19,    0,    0,   21,
        0,    0,    0,    0,    0,    3,    0,    0,    0,    0,
        0,    0,   12,    0,   11,    0,    0,   15,    0,    0,
       18,    0,   21,    0,    0,    0,    0,    0,    4,    0,
        0,   16,   12,   11,    0,    0,    0,    0,   22,    6,
        4,   29,    0,   16,    0,    0,    0,   23,   29,    0,

        0,    0,    0,    0,    0,    0,    0,   28,    0,   14,
       24,    0,   20,   24,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    6,    1,    7,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
       10,    1,    1,    1,   11,   12,    1,    1,   13,    1,
        1,   14,   15,    1,    1,   16,   17,   18,   19,    1,
        1,   20,   21,   22,    1,    1,    1,   23,    1,    1,
        1,    1,    1,    1,    1,    1,   24,   25,   26,   27,

       28,    1,   29,   30,   31,    1,   32,   33,   34,   35,
       36,   37,    1,   38,   39,   40,    1,   41,   42,   43,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[44] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[321] =
    {   0,
        0,    4,    8,   25,   33,   41,   49,   53,   67,  100,
       58,   72,  133,  656,   79,   94,  160,  655,  112,  120,
       86,  128,  137,  145,  659,  662,   17,  662,  662,  662,
      630,   21,  633,   37,  647,  646,  662,  619,  164,  618,
      620,  614,  626,  614,  198,  613,  608,  612,  613,  601,
      608,  225,  607,  602,  612,  607,  598,  628,    0,  106,
        0,    0,    0,  152,    0,    0,  170,  662,  607,  177,
       63,  600,  178,  116,  625,  624,  601,  189,  599,  593,
      605,  601,  596,  587,  582,  593,    0,  584,  588,  589,
      577,  592,  578,    9,  586,  579,  584,    0,  575,  585,

      580,  571,  583,   24,  569,  577,  583,  597,    0,  202,
        0,    0,  206,    0,  574,  141,  577,  156,  563,  583,
      566,  229,  569,  559,  577,  569,  553,  560,  559,  557,
      552,  569,  549,  561,  564,  552,  548,  550,  563,  193,
      563,  542,  230,  240,  541,  210,  569,  542,  250,  251,
      538,  255,  217,  563,  548,  547,  264,  534,  533,  216,
      544,  254,  548,  542,  269,    6,   50,   77,  277,  265,
      554,  278,  281,  288,  296,  301,  540,  309,  314,  268,
      554,  322,  529,  323,  332,  537,  327,  544,  552,  548,
      533,  545,  521,   91,  295,  340,  326,  523,  341,  344,

      350,   98,  354,  144,  362,  162,  366,  168,  519,  377,
      175,  200,  254,  536,  345,  386,  387,  394,  306,  213,
      368,  517,  402,  403,  518,  662,  524,  502,  493,  468,
      495,  474,  406,  470,  445,  407,  456,  411,  415,  419,
      425,  413,  284,  429,  429,  439,  436,  440,  447,  371,
      446,  399,  455,  401,  394,  662,  403,  456,  383,  389,
      353,  383,  455,  378,  461,  354,  308,  290,  274,  469,
      236,  227,  216,  194,  180,  165,  184,  470,  282,  156,
      156,  363,  480,  484,  134,  109,   94,   85,  662,  662,
      473,  480,  492,  493,  496,   61,  497,  662,  501,  506,

      509,  510,  513,   39,  517,  521,  522,   40,  530,   23,
      531,  534,    9,  538,  662,  543,  546,  549,    0,  552
    } ;

static yyconst short int yy_def[321] =
    {   0,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,   13,  316,  316,  316,   17,  316,  316,
      317,  317,  318,  318,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  319,  319,
      319,  319,  320,  320,  320,  320,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,   45,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,   52,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  319,  319,
      319,  320,  320,  320,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,    0,  315,  315,  315,  315,  315
    } ;

static yyconst short int yy_nxt[706] =
    {   0,
      109,   27,   28,   27,   29,   27,   28,   27,   30,   27,
       28,   27,   29,  167,  168,   31,   35,  313,   67,   32,
       67,   68,   70,   33,   70,   34,   27,   28,   27,   30,
       71,  310,  127,   35,   27,   28,   27,   29,   73,  128,
       73,   36,   27,   28,   27,   30,   74,  133,  308,   36,
       27,   37,   27,   29,   27,   37,   27,   30,  194,   27,
       37,   27,   29,   38,  116,  134,  116,   38,   39,   37,
       39,   29,   44,   27,   37,   27,   30,  195,  311,   40,
       27,   37,   27,   29,  167,  168,   44,   27,   28,   60,
       61,  304,   41,   51,   42,   27,   37,   27,   30,  194,

       43,   39,   37,   39,   30,  203,  204,   67,   51,  110,
      111,  298,   40,   27,   28,   27,   29,  118,  195,  118,
       58,   27,   28,   27,   30,   41,  297,   42,   58,   27,
       28,   60,   62,   43,   45,   37,   45,   29,   64,   28,
       64,   65,  116,  296,  116,   46,   64,   28,   64,   66,
       47,  203,  204,  113,   48,  113,  114,  118,   49,  118,
       50,   52,   37,   52,   29,   78,  295,   78,   68,  207,
      208,   67,   53,   67,   68,  207,  208,   54,   70,   73,
       70,   73,  212,  213,   55,   56,   71,   74,  293,   79,
       78,   80,   78,   68,  162,  292,  162,   81,   57,   87,

      290,   87,   68,   67,  289,  110,  111,  113,  243,  113,
      114,  170,  288,  170,   79,   88,   80,  287,  180,   89,
      180,  250,   81,   90,  273,   91,   98,  244,   98,   68,
      143,  143,  143,  143,  188,  273,  189,  190,  144,  144,
      251,  165,   99,  165,  271,  166,  166,  167,  168,  100,
      101,  173,  175,  173,  175,  162,  178,  162,  178,  174,
      176,  212,  213,  102,  179,  184,  170,  184,  170,  180,
      165,  180,  165,  185,  166,  166,  167,  168,  196,  199,
      196,  199,  173,  291,  173,  291,  197,  200,  286,  201,
      174,  201,  243,  202,  202,  203,  204,  175,  268,  175,

      231,  231,  205,  232,  205,  176,  206,  206,  207,  208,
      178,  244,  178,  220,  221,  210,  268,  210,  179,  211,
      211,  212,  213,  215,  184,  215,  184,  233,  223,  233,
      223,  216,  185,  218,  234,  218,  224,  219,  219,  220,
      221,  196,  199,  196,  199,  236,  215,  236,  215,  197,
      200,  201,  237,  201,  216,  202,  202,  203,  204,  202,
      202,  203,  238,  205,  294,  205,  294,  206,  206,  207,
      208,  206,  206,  207,  240,  220,  221,  285,  210,  250,
      210,  239,  211,  211,  212,  213,  265,  246,  248,  246,
      248,  263,  282,  241,  247,  218,  249,  218,  251,  219,

      219,  220,  221,  223,  253,  223,  253,  233,  236,  233,
      236,  224,  281,  280,  234,  237,  202,  202,  203,  238,
      262,  262,  277,  263,  206,  206,  207,  240,  254,  276,
      264,  264,  255,  265,  267,  267,  275,  268,  239,  274,
      246,  248,  246,  248,  247,  269,  241,  247,  270,  249,
      270,  272,  272,  266,  273,  271,  253,  278,  253,  278,
      202,  202,  203,  283,  237,  279,  206,  206,  207,  284,
      270,  278,  270,  278,  291,  261,  291,  271,  234,  279,
      254,  299,  232,  299,  255,  202,  202,  203,  283,  206,
      206,  207,  284,  300,  294,  300,  294,  302,  305,  302,

      305,  301,  299,  232,  299,  303,  306,  300,  260,  300,
      307,  302,  307,  302,  309,  301,  309,  308,  305,  303,
      305,  310,  312,  307,  312,  307,  306,  259,  258,  313,
      308,  309,  314,  309,  314,  312,  257,  312,  310,  314,
      256,  314,  313,   26,   26,   26,   59,   59,   59,   63,
       63,   63,  112,  112,  252,  245,  242,  235,  230,  229,
      228,  227,  226,  225,  222,  217,  214,  209,  198,  193,
      192,  191,  187,  186,  183,  182,  181,  177,  172,  171,
      169,  164,  163,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,

      142,  141,  140,  139,  138,  108,  137,  136,  135,  132,
      107,  106,  105,  104,  131,  130,  129,  126,  125,   96,
       95,   94,   93,  124,  123,  122,  121,  120,   85,   84,
       83,  119,   76,   75,  117,  115,  108,  107,  106,  105,
      104,  103,   97,   96,   95,   94,   93,   92,   86,   85,
       84,   83,   82,   77,   76,   75,   72,   69,  315,   30,
       30,   25,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315
    } ;

static yyconst short int yy_chk[706] =
    {   0,
      319,    1,    1,    1,    1,    2,    2,    2,    2,    3,
        3,    3,    3,  166,  166,    2,    3,  313,   27,    2,
       27,   27,   32,    2,   32,    2,    4,    4,    4,    4,
       32,  310,   94,    4,    5,    5,    5,    5,   34,   94,
       34,    5,    6,    6,    6,    6,   34,  104,  308,    6,
        7,    7,    7,    7,    8,    8,    8,    8,  167,   11,
       11,   11,   11,    7,   71,  104,   71,    8,    9,    9,
        9,    9,   11,   12,   12,   12,   12,  167,  304,    9,
       15,   15,   15,   15,  168,  168,   12,   21,   21,   21,
       21,  296,    9,   15,    9,   16,   16,   16,   16,  194,

        9,   10,   10,   10,   10,  202,  202,   60,   16,   60,
       60,  288,   10,   19,   19,   19,   19,   74,  194,   74,
       19,   20,   20,   20,   20,   10,  287,   10,   20,   22,
       22,   22,   22,   10,   13,   13,   13,   13,   23,   23,
       23,   23,  116,  286,  116,   13,   24,   24,   24,   24,
       13,  204,  204,   64,   13,   64,   64,  118,   13,  118,
       13,   17,   17,   17,   17,   39,  285,   39,   39,  206,
      206,   67,   17,   67,   67,  208,  208,   17,   70,   73,
       70,   73,  211,  211,   17,   17,   70,   73,  281,   39,
       78,   39,   78,   78,  140,  280,  140,   39,   17,   45,

      277,   45,   45,  110,  276,  110,  110,  113,  212,  113,
      113,  146,  275,  146,   78,   45,   78,  274,  153,   45,
      153,  220,   78,   45,  273,   45,   52,  212,   52,   52,
      122,  143,  122,  143,  160,  272,  160,  160,  122,  143,
      220,  144,   52,  144,  271,  144,  144,  144,  144,   52,
       52,  149,  150,  149,  150,  162,  152,  162,  152,  149,
      150,  213,  213,   52,  152,  157,  170,  157,  170,  180,
      165,  180,  165,  157,  165,  165,  165,  165,  169,  172,
      169,  172,  173,  279,  173,  279,  169,  172,  269,  174,
      173,  174,  243,  174,  174,  174,  174,  175,  268,  175,

      195,  195,  176,  195,  176,  175,  176,  176,  176,  176,
      178,  243,  178,  219,  219,  179,  267,  179,  178,  179,
      179,  179,  179,  182,  184,  182,  184,  197,  187,  197,
      187,  182,  184,  185,  197,  185,  187,  185,  185,  185,
      185,  196,  199,  196,  199,  200,  215,  200,  215,  196,
      199,  201,  200,  201,  215,  201,  201,  201,  201,  203,
      203,  203,  203,  205,  282,  205,  282,  205,  205,  205,
      205,  207,  207,  207,  207,  221,  221,  266,  210,  250,
      210,  203,  210,  210,  210,  210,  264,  216,  217,  216,
      217,  262,  261,  207,  216,  218,  217,  218,  250,  218,

      218,  218,  218,  223,  224,  223,  224,  233,  236,  233,
      236,  223,  260,  259,  233,  236,  238,  238,  238,  238,
      239,  239,  257,  239,  240,  240,  240,  240,  224,  255,
      241,  241,  224,  241,  244,  244,  254,  244,  238,  252,
      246,  248,  246,  248,  247,  245,  240,  246,  249,  248,
      249,  251,  251,  242,  251,  249,  253,  258,  253,  258,
      263,  263,  263,  263,  237,  258,  265,  265,  265,  265,
      270,  278,  270,  278,  291,  235,  291,  270,  234,  278,
      253,  292,  232,  292,  253,  283,  283,  283,  283,  284,
      284,  284,  284,  293,  294,  293,  294,  295,  297,  295,

      297,  293,  299,  231,  299,  295,  297,  300,  230,  300,
      301,  302,  301,  302,  303,  300,  303,  301,  305,  302,
      305,  303,  306,  307,  306,  307,  305,  229,  228,  306,
      307,  309,  311,  309,  311,  312,  227,  312,  309,  314,
      225,  314,  312,  316,  316,  316,  317,  317,  317,  318,
      318,  318,  320,  320,  222,  214,  209,  198,  193,  192,
      191,  190,  189,  188,  186,  183,  181,  177,  171,  164,
      163,  161,  159,  158,  156,  155,  154,  151,  148,  147,
      145,  142,  141,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,

      121,  120,  119,  117,  115,  108,  107,  106,  105,  103,
      102,  101,  100,   99,   97,   96,   95,   93,   92,   91,
       90,   89,   88,   86,   85,   84,   83,   82,   81,   80,
       79,   77,   76,   75,   72,   69,   58,   57,   56,   55,
       54,   53,   51,   50,   49,   48,   47,   46,   44,   43,
       42,   41,   40,   38,   36,   35,   33,   31,   25,   18,
       14,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "read_input.l"
#define INITIAL 0
#line 15 "read_input.l"
#include<stdlib.h>
#include<stdio.h>
#include<string.h>
#include"cudaglobal.h"
#include"global.h"
#include"read_input.h"

int line_of_file=1;
int comment_caller;
int a,b;
float c;
char name[100];
  
  
// Overrelaxation parameters
int orxmaxit;
int orxcheckinterval;
double orxeps;  
int orxflag = 0;


// Sim. ann. parameters
SAPARAM_LIST saparam;
int saflag = 0;
//saparam.checkint = 1;

// Therm. parameters
THERMPARAM_LIST thermparam;
int thermflag = 0;
//thermparam.checkint = 1;

int randseed;
  
  /* Name of the parsing routine */
#define YY_DECL         int parse_input()
#define YY_NO_UNPUT
#define YY_NEVER_INTERACTIVE 1
#define TT 1

#define LL 2

#define INITORX 3

#define OVERRELAX 4

#define INITSA 5

#define SIMANN 6

#define INITTHERM 7

#define THERM 8

#define RND 9

#define ERROR 10

#define COMMENT 11

#line 692 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 73 "read_input.l"


#line 849 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 316 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 662 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 75 "read_input.l"
BEGIN(TT);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 76 "read_input.l"
BEGIN(LL);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "read_input.l"
BEGIN(INITORX);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "read_input.l"
BEGIN(RND);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "read_input.l"
BEGIN(INITSA);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 80 "read_input.l"
BEGIN(INITTHERM);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "read_input.l"
{
  T = atoi(yytext);
  printf("T = %s\n", yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 87 "read_input.l"
{
  L = atoi(yytext);
  printf("L = %s\n", yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "read_input.l"
{
  randseed = atoi(yytext);
  printf("Random Seed = %s\n", yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "read_input.l"
{
 printf("Found sim. annealing block in line %d\n", line_of_file); 
 BEGIN(SIMANN);
 }
	YY_BREAK

case 11:
YY_RULE_SETUP
#line 104 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %f", name, &c);
    saparam.Tmin = c;
    printf(" SA Tmin set to %e in line %d\n", c, line_of_file);
  }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 109 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %f", name, &c);
    saparam.Tmax = c;
    printf(" SA Tmax set to %e in line %d\n", c, line_of_file);
  } 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 114 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    saparam.N = a;
    printf(" SA steps set to %d line %d\n", a, line_of_file);
  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 119 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    saparam.checkint = a;
    printf(" SA check interval set to %d line %d\n", a, line_of_file);
  }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 124 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %f", name, &c);
    saparam.expo = c;
    printf(" SA temperature expo set to %e in line %d\n", c, line_of_file);
  }  
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 129 "read_input.l"
{
  saflag=1;
  printf("End sim. annealing block in line %d\n\n", line_of_file);
  BEGIN(0);
  }
	YY_BREAK

case 17:
YY_RULE_SETUP
#line 141 "read_input.l"
{
 printf("Found thermalization block in line %d\n", line_of_file); 
 BEGIN(THERM);
 }
	YY_BREAK

case 18:
YY_RULE_SETUP
#line 146 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    thermparam.Nsweep = a;
    printf(" Nsweep set to %d line %d\n", a, line_of_file);
  }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 151 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    thermparam.Nsave = a;
    printf(" Nsave set to %d line %d\n", a, line_of_file);
  }  
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 156 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    thermparam.checkint = a;
    printf(" Therm. check interval set to %d line %d\n", a, line_of_file);
  }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 161 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %f", name, &c);
    thermparam.beta = c;
    printf(" beta set to %e in line %d\n", c, line_of_file);
  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 166 "read_input.l"
{
    thermparam.startcond = 1;
    printf(" using hot start in line %d\n", line_of_file);
  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 170 "read_input.l"
{
    thermparam.startcond = 0;
    printf(" using cold start in line %d\n", line_of_file);
  }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 174 "read_input.l"
{
  thermflag=1;
  printf("End thermalization block in line %d\n\n", line_of_file);
  BEGIN(0);
  }
	YY_BREAK

case 25:
YY_RULE_SETUP
#line 183 "read_input.l"
{
 printf("Found overrelaxation block in line %d\n", line_of_file); 
 BEGIN(OVERRELAX);
 }
	YY_BREAK

case 26:
YY_RULE_SETUP
#line 188 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %f", name, &c);
    orxeps = c;
    printf(" Overrelaxation dAdA epsilon set to %e in line %d\n", c, line_of_file);
  }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 193 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    orxmaxit = a;
    printf(" Overrelaxation max iterations set to %d line %d\n", a, line_of_file);
  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 198 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    orxcheckinterval = a;
    printf(" Overrelaxation check interval set to %d line %d\n", a, line_of_file);
  }  
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 203 "read_input.l"
{
  orxflag=1;
  printf("End overrelaxation block in line %d\n\n", line_of_file);
  BEGIN(0);
  }
	YY_BREAK

case 30:
YY_RULE_SETUP
#line 218 "read_input.l"
{
   comment_caller = YY_START;   
   BEGIN(COMMENT);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 222 "read_input.l"
{
   comment_caller = YY_START;
   BEGIN(COMMENT);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 226 "read_input.l"
{
  BEGIN(comment_caller);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 230 "read_input.l"
{
  BEGIN(ERROR);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 233 "read_input.l"
{
  printf("Parsing error in line %d\nAborting...!\n", line_of_file);
  printf("%s\n",yytext);
  exit(1);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 240 "read_input.l"
{
  line_of_file++;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 243 "read_input.l"
{
  line_of_file++;
  BEGIN(0);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 252 "read_input.l"
ECHO;
	YY_BREAK
#line 1227 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(TT):
case YY_STATE_EOF(LL):
case YY_STATE_EOF(INITORX):
case YY_STATE_EOF(OVERRELAX):
case YY_STATE_EOF(INITSA):
case YY_STATE_EOF(SIMANN):
case YY_STATE_EOF(INITTHERM):
case YY_STATE_EOF(THERM):
case YY_STATE_EOF(RND):
case YY_STATE_EOF(ERROR):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 316 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 316 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 315);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 252 "read_input.l"



/*
 *  Dummy (but not dumb) routine - well, function
 */

int yywrap()
{
  return(1);
}


int read_input(char * conf_file){

  if ((yyin = fopen(conf_file, "rt")) == NULL){
    return(2);
  }
  
  yyout = fopen("/dev/null", "w");
  
  parse_input();  
 
  
  LX=L;
  LY=L;
  LZ=L;
  VOLUME=LX*LY*LZ*T;
   
  fclose(yyout);
  fclose(yyin);
  return(0);
}


